const express = require('express');
const router = express.Router();
const users = require('../modals/userModal');
const { getproduct, addproduct, updateproduct, deleteproduct, findids } = require('../controllers/productController');
router.get('/getProducts', getproduct);
router.post('/addProducts', addproduct);
router.put('/updateProducts', updateproduct);
router.delete('/deleteProducts/:_id', deleteproduct);
router.delete('/findById', findids);
module.exports = router;